- Controller/Payment/PaymentReturn.php
- Model/PaymentMethod.php
Prevent order from being processing if payment was not validated
> Prevent order saving and use transaction

- Controller/Payment/AbstractPayment.php
- Controller/Payment/Cancel.php
- Controller/Payment/Ipn.php
- Controller/Payment/PaymentReturn.php
- CustomerData/Cards.php
- Gateway/Helper/SubjectReader.php
- Gateway/Request/Payment/CustomerDataBuilder.php
- Gateway/Response/InstallmentPlan/FetchTransactionInformationHandler.php
- Model/Customer/Card.php
- Model/Order/InstallmentPlan.php
- Model/Order/Payment.php
- Model/Order/Processing.php
- Model/ResourceModel/Customer/Card/Collection.php
- Model/ResourceModel/Order/InstallmentPlan/Collection.php
- Model/ResourceModel/Order/Payment/Collection.php
- Model/ResourceModel/Order/Processing/Collection.php
- README.md
- Setup/UpgradeSchema.php
- composer.json
- etc/di.xml
- etc/module.xml
- view/adminhtml/templates/info/installment_plan.phtml
- view/frontend/templates/checkout/formjs.phtml
- view/frontend/templates/customer/cardList.phtml
- Adapt to Magento coding standards
- Fix IPN issues (csrf validation + wrong property used)
- Improve install documentation
- Fix Installment plan update before payment is validated
> Fix IPN + Order Status + Documentation + Coding standards

- Gateway/Config/PayplugPayment.php
- Gateway/Response/Standard/PaymentHandler.php
- Helper/Config.php
- Helper/Data.php
- Helper/Transaction/OndemandBuilder.php
- composer.json
- etc/adminhtml/system.xml
- etc/config.xml
- etc/di.xml
- i18n/en_US.csv
- i18n/es_ES.csv
- i18n/fr_FR.csv
- i18n/it_IT.csv
An option has been added to generate invoices only when the payment is successful.
> Invoice generated on successful payments only

- Controller/Adminhtml/Order/SendNewPaymentLink.php
- Controller/Adminhtml/Order/UpdatePayment.php
- Controller/Payment/Ipn.php
- Controller/Payment/PaymentReturn.php
- Exception/OrderAlreadyProcessingException.php
- Helper/Data.php
- composer.json
- i18n/en_US.csv
- i18n/es_ES.csv
- i18n/fr_FR.csv
- i18n/it_IT.csv
> Exception should not lead to order cancellation

- Helper/Config.php
- Model/Payment/Standard/ConfigProvider.php
- composer.json
- view/frontend/layout/onestepcheckout_index_index.xml
- view/frontend/web/css/source/_module.less
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_oney-method.js
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_standard-method.js
- view/frontend/web/template/payment/payplug_payments_standard.html
> Release 1.15.0

- Helper/Config.php
- composer.json
> Bump to 1.16.0

- Helper/Config.php
- Helper/Transaction/AbstractBuilder.php
- composer.json
> MAG-80 : Handle different types of address object

- Helper/Data.php
> #MAG-139 Fix wrong formatted if

- Helper/Data.php
> #MAG-144 Abort schedule payment before aborting installment plan

- Helper/Config.php
- Helper/Oney.php
- Observer/PaymentConfigObserver.php
> #MAG-135 Hide MEA depending on merchand country / store locale

- Helper/Config.php
- composer.json
> Bump to 1.20.0

- Helper/Config.php
- Helper/Data.php
- Helper/Oney.php
- Observer/PaymentConfigObserver.php
- composer.json
> Release 1.20.0

- Controller/Payment/Ipn.php
- Controller/Payment/PaymentReturn.php
- Helper/Config.php
- Helper/Data.php
- Model/OrderPaymentRepository.php
- composer.json
> release 1.20.1

- Controller/Bancontact/IsAvailable.php
- i18n/fr_FR.csv
- i18n/it_IT.csv
- view/frontend/web/css/source/_module.less
> MAG-169 Bancontact fixes

- view/frontend/web/css/source/_module.less
> MAG-171 Change Bancontact error color

- Helper/Config.php
- composer.json
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_apple_pay-method.js
> SMP-845 Use total including tax for ApplePay session

- Helper/Config.php
- composer.json
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_apple_pay-method.js
> release 1.23.1

- Controller/Amex/IsAvailable.php
- Controller/Payment/PaymentReturn.php
- Gateway/Config/Amex.php
- Helper/Config.php
- Helper/Data.php
- Helper/Transaction/AmexBuilder.php
- Model/Payment/Amex/ConfigProvider.php
- Observer/PaymentConfigObserver.php
- composer.json
- etc/adminhtml/system.xml
- etc/config.xml
- etc/di.xml
- etc/frontend/di.xml
- i18n/en_US.csv
- i18n/es_ES.csv
- i18n/fr_FR.csv
- i18n/it_IT.csv
- view/frontend/layout/checkout_index_index.xml
- view/frontend/web/css/source/_module.less
- view/frontend/web/images/amex.svg
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_amex-method.js
- view/frontend/web/js/view/payment/payplug_payments_amex.js
- view/frontend/web/template/payment/payplug_payments_amex.html
> MAG-182 Amex payment

- Observer/PaymentConfigObserver.php
> MAG-183 Amex is never available in TEST mode

- Helper/Config.php
- Helper/Transaction/ApplePayBuilder.php
- Model/Payment/ApplePay/ConfigProvider.php
- composer.json
> SMP-913 Get current store configuration to retrieve domain name

- .github/workflows/jira.yaml
- [] Check that plugin version has been upgrated and are identical in both `composer.json` and `Helper/Config.php` files
> Merge master into qa

- .github/workflows/jira.yaml
- Helper/Transaction/OndemandBuilder.php
- Observer/PaymentConfigObserver.php
> MAG-215 Use laminas to validate fields

- Observer/StandardAvailabilityObserver.php
> MAG-179 Check if merchant domain has been allowed to display ApplePay payment method

- Model/Payment/Standard/ConfigProvider.php
> MAG-207 Fix one click display

- Model/Payment/Standard/ConfigProvider.php
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_standard-method.js
- view/frontend/web/template/payment/payplug_payments_standard.html
> MAG-202 Integrated Payment fixes

- Helper/Config.php
- composer.json
> MAG-202 Update module version

- Helper/Config.php
- composer.json
> Rollback module version to 1.24.1

- etc/adminhtml/system.xml
> WOOC-980 add magento js validation on fields

- Helper/Config.php
- Observer/PaymentConfigObserver.php
> WOOC-976 add scope to the saceOneyConfig

- .github/workflows/phpcs.yml
> feat: add sonar-cloud job

- Controller/Ppro/IsAvailable.php
- view/frontend/web/css/source/_module.less
- view/frontend/web/js/view/payment/method-renderer/ppro-payment-renderer.js
- view/frontend/web/template/payment/payplug_payments_ppro.html
> MAG-218 PPRO methods fixes

- Helper/Config.php
- composer.json
> SMP-1966 bugs on sintaxe

- Observer/PaymentReturnObserver.php
- etc/di.xml
- etc/events.xml
> MAG-231 add Payment Return event

- Helper/Config.php
- composer.json
> update-version 1.27.2

- Helper/Config.php
- Observer/PaymentConfigObserver.php
> WOOC-989 default values for init values

- Controller/Payment/Cancel.php
> SMP-1932 try a restorequote from Magento

- Controller/Payment/PaymentReturn.php
> MAG-236 : Fix 3DS close redirect + cart rebuild

- Helper/Config.php
- composer.json
> update plugin version

- Observer/PaymentConfigObserver.php
> MAG-249 preventing mag errors

- README.md
> chore: dani contributor

- Controller/Payment/CheckPayment.php
- Helper/Data.php
- etc/di.xml
- view/frontend/web/js/view/payment/method-renderer/payplug_payments_standard-method.js
> MAG-349: Update order status

- Controller/Payment/PaymentReturn.php
> MAG-368: Fix Undefined array key after 3DS failed payment

- view/adminhtml/templates/form/ondemand.phtml
- view/adminhtml/templates/info/default.phtml
- view/adminhtml/templates/info/installment_plan.phtml
- view/adminhtml/templates/info/ondemand.phtml
- view/frontend/templates/checkout/formjs.phtml
- view/frontend/templates/customer/cardList.phtml
- view/frontend/templates/info/default.phtml
- view/frontend/templates/info/installment_plan.phtml
- view/frontend/templates/info/ondemand.phtml
- view/frontend/templates/oney/simulation.phtml
- view/frontend/templates/oney/simulation_content.phtml
- view/frontend/templates/oney/simulation_wrapper.phtml
- view/frontend/templates/oney/simulation_wrapper_checkout.phtml
> MAG-316: Fix phtmls escapers and add strict types for php 8

- view/frontend/web/css/source/module/_checkout.less
> MAG-366: Fix payment method title CSS selector

- etc/csp_whitelist.xml
[MAG-421](https://payplug-prod.atlassian.net/browse/MAG-421): Update csp_whitelist.xml, clean it and add script-src-elem policy element as suggested by @bhennesAdv
Changelog: Fixed
[MAG-421]: https://payplug-prod.atlassian.net/browse/MAG-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feature/MAG-421 to release/v4.3.0

- view/frontend/web/js/view/apple-pay/cart-button.js
> MAG-407: Add Apple Pay workflowType parameter to place order fetch

- Helper/Data.php
MAG-443: Fix the order processing function
Changelog: Fixed
- [V] Check that plugin version has been upgraded and are identical in both `composer.json` and `Helper/Config.php` files
> hotfix/MAG-443 into release/v4.3.3

- Controller/Payment/Ipn.php
- Helper/Transaction/AbstractBuilder.php
MAG-453: Add the reserved order id to the metadata if we are on a deferred payment.
Changelog: Added
> MAG-453 into release/v4.3.4

- Controller/Payment/PaymentReturn.php
MAG-441: Fix the PaymentReturn.php not working with the installment plans due to a different SQL table
Changelog: Fixed
> MAG-441 into release/v4.3.4

- Block/OndemandInfo.php
- view/adminhtml/templates/info/default.phtml
- view/adminhtml/templates/info/installment_plan.phtml
- view/adminhtml/templates/info/ondemand.phtml
- view/frontend/templates/info/default.phtml
- view/frontend/templates/info/installment_plan.phtml
- view/frontend/templates/info/ondemand.phtml
- [V] Check that plugin version has been upgraded and are identical in both `composer.json` and `Helper/Config.php` files
> Feature/MAG-440 into release/v4.3.4

- Block/ApplePay/Button.php
- Block/Formjs.php
- Controller/ApplePay/CreateMockOrder.php
- Controller/ApplePay/UpdateCartOrder.php
- Controller/ApplePay/UpdateTransaction.php
- Helper/ApplePay.php
- Helper/Config.php
- Model/Payment/ApplePay/ConfigProvider.php
- etc/adminhtml/system.xml
- etc/config.xml
- view/frontend/layout/catalog_product_view.xml
- view/frontend/layout/checkout_cart_index.xml
- view/frontend/templates/apple-pay/cart-button.phtml
- view/frontend/templates/apple-pay/product-button.phtml
- view/frontend/web/css/source/module/payments/_apple-pay.less
- view/frontend/web/js/view/apple-pay/cart-button.js
- view/frontend/web/js/view/apple-pay/product-button.js
- view/frontend/web/js/view/payment/payplug_payments_apple_pay.js
- [V] Check that plugin version has been upgraded and are identical in both `composer.json` and `Helper/Config.php` files
> feature/apple-pay into release/v4.4.0

- Block/ApplePay/AbstractButton.php
- Block/ApplePay/ProductButton.php
- Controller/ApplePay/CreateMockOrder.php
- Controller/ApplePay/GetAvailablesShippingMethods.php
- view/frontend/templates/product/button-apple-pay.phtml
> MAG-403: ApplePay - Get current product with product repository

- .github/workflows/issue-response.yml
> chore: action workflow to add an automatic issue answer

- Observer/PaymentConfigObserver.php
> MAG-378: Remove debug
